stencila/designa

guide/index.html
sass/_tool-tip.sass

Some tweaks to make tool tips more similar to mock ups:
After these changes (background, border and reduced padding):
Also have extended from `.has-drop-shadow` so that HTML can be simplified to `<span class="tool-tip">`

Change background, border and padding for tool tips

---

sass/atoms/_modal.sass
sass/bulma/elements/_tabs.sass
sass/config/bulma-overrides/_footer.sass
sass/stencila.sass

**fix: modal colors and CTA.**
- Removing $blue color from modal headers/footers, updating font color to dark default.
- Removing white border from modal footer buttons.
**fix(tabs): Updating segmented control to $dark color instead of green to simplify colors.**

Hub related tweaks

---

packages/style-material/src/atoms/button/_base.css
packages/style-material/src/atoms/tooltip.css
packages/style-stencila/src/atoms/button/_base.css
packages/style-stencila/src/atoms/tooltip.css
packages/style-stencila/src/molecules/codeExpression.css

- Fixes an empty space being shown for CodeExpression component when the Source Code 
- Fix Toolbar buttons having an underline in the Tufte Thema theme
- Fix extra wide tooltips in Wilmore Thema theme

Fix code expression buttons

---

packages/components/src/components/executableDocumentToolbar/executa.ts
packages/components/src/components/executableDocumentToolbar/executableDocumentToolbar.tsx

This PR:
- ~exposes the Job polling frequency under the `jobPollFrequency` prop (`job-poll-frequency` attribute)~ dropped to be refined in an upcoming PR
- sets the `credentials: 'include'` option when making network requests. Docs can be found [here](https://fetch.spec.whatwg.org/#concept-request-credentials-mode) with [examples here](https://fetch.spec.whatwg.org/#cors-protocol-and-credentials).

Exec toolbar request refinements

---

packages/components/package-lock.json
packages/components/package.json
packages/components/src/components/button/button.tsx
packages/components/src/components/codeChunk/codeChunk.tsx
packages/components/src/components/executableDocumentToolbar/executableDocumentToolbar.tsx
packages/components/src/components/executableDocumentToolbar/sessionStatus.tsx
packages/style-material/package-lock.json
packages/style-material/package.json
packages/style-material/src/atoms/icon.css
packages/style-stencila/package-lock.json
packages/style-stencila/package.json
packages/style-stencila/src/atoms/icon.css
packages/style-stencila/src/objects/executableToolbar.css
stories/molecules/toolbar/toolbar.stories.js

Picks up the work originally included, but then removed from #82.
This change allows the executable toolbar to continue polling the Hub even after successfully initiating a Session, in order to notify the user of any status changes.
Also fixes loader icons not spinning 🌀

Exec toolbar request refinements: part 2

---

packages/components/src/components.d.ts
packages/components/src/components/codeExpression/codeExpression.tsx
packages/components/src/components/codeExpression/readme.md
packages/components/src/components/details/details.tsx
packages/components/src/components/details/readme.md
packages/components/src/components/error/error.tsx
packages/components/src/components/executableDocumentToolbar/executableDocumentToolbar.tsx
packages/style-stencila/src/objects/executableToolbar.css
stories/molecules/codeExpression/codeExpression.stories.js

- fix(CodeExpression): Pass language prop to execution handler (close #38)
- refactor(Exec Toolbar): Remove CSS scoping for to fix sibling element margins
- fix(Exec Toolbar): Give status text more room on small screens
- docs(Details): Fix JSDoc string
- fix(Error): Fix typo in default message

Fix CodeExpression execution & misc visual refinements

---

packages/components/package-lock.json
packages/components/package.json
packages/components/src/components/executableDocumentToolbar/executableDocumentToolbar.tsx
packages/components/src/components/executableDocumentToolbar/readme.md
packages/components/src/components/executableDocumentToolbar/sessionStatus.tsx
packages/style-stencila/src/objects/executableToolbar.css

In using the executable documents of any moderate length, we found a need to navigate to the code node being currently executed, especially if the process was taking some time. This PR adds a progress indicator, which when clicked scrolls the element into view.
The updating message also reassures the user that progress is being made, and that the computation hasn't stalled.
I decided to keep the UI affordances subtle as I deemed this to be a non-essential interaction.
Would appreciate feedback if you have any thoughts @chugginselifesciences or @gmaciocci.
Otherwise I'll be merging this sometime tomorrow.
**On a larger document:**

feat(Exec Toolbar): Add execution progress indicator

---

packages/components/package-lock.json
packages/components/package.json

With the [latest changes](https://github.com/stencila/designa/pull/145) some of the dependencies were listed under `devDependcies`, meaning that they weren't installed when the component library was used in another project.
This PR fixes the issue.

Editor: Ensure dependencies are installed in consuming projects

---

README.md

I went looking for the latest version of `@stencila/components`, came here first thinking I would use latest GitHub release as I do for other repos (but of course this is a monorepo so different releases for different packages). Anyway, this just makes that search for version numbers a little more convienient.

docs(README): Add NPM badges for each package

---

packages/components/src/components.d.ts
packages/components/src/components/codeExpression/codeExpression.tsx
packages/components/src/components/codeExpression/readme.md
packages/components/src/components/nodeList/nodeRenderer.tsx
packages/style-stencila/src/molecules/codeExpression.css
stories/molecules/codeExpression/codeExpression.stories.js

- Refines the handling of whitespaces and newlines in code expression outputs to make them fit better with surrounding text content 
- Fixes a regression with rendering of image and other HTML elements in the output section

Fix code expression output rendering

---

packages/components/src/components.d.ts
packages/components/src/components/actionMenu/actionMenu.tsx
packages/components/src/components/codeChunk/codeChunk.tsx
packages/components/src/components/codeChunk/readme.md
packages/style-material/src/atoms/tooltip.css
packages/style-stencila/src/atoms/tooltip.css
packages/style-stencila/src/molecules/actionMenu.css
packages/style-stencila/src/molecules/codeChunk.css
stories/molecules/codeChunk/codeChunk.stories.js

This PR adds logic at the time of `CodeChunk` component load to calculate the rendered width of the editor.
If it's below a certain width, then we vertically stack the editor and outputs.
Previously we were using media queries to do this, but that only takes into account the viewport width and not the parent element width. This was especially noticeable in Thema themes with relatively narrow article widths, or ones which didn't allow the CodeChunk component to break out of the article width constraint.
On mobile breakpoints the layout toggle button is hidden, as the layout is always stacked on narrow breakpoints.
https://user-images.githubusercontent.com/1646307/107988425-fa9bdf80-6f9d-11eb-854b-1b39affe8604.mp4

Code chunk layout toggle

---

packages/components/package-lock.json
packages/components/package.json
packages/components/src/components.d.ts
packages/components/src/components/editor/editor.tsx
packages/components/src/components/editor/readme.md
packages/components/src/components/executableDocumentToolbar/readme.md
packages/components/src/components/toast/readme.md
packages/components/src/components/toast/toast.tsx
packages/components/src/components/toast/toastController.ts
packages/components/src/components/toastContainer/readme.md
packages/components/src/components/toastContainer/toastContainer.tsx
stories/atoms/toast/toast.stories.js

This PR:
- refactors the editor `get/setState` methods to include the edit history as part of the JSON serialization/deserialization process. This greatly simplifies the storage and rehydration of the editor state in the Desktop client.
- Bumps the minimum version requirement for `@stencila/schema` to ensure that the correct node type guards are available
- adds a new `stencila-toast-container` component. This allows for finer-grained usage of the toast notifications in other applications, such as showing actionable toast messages in the Desktop.
- updates the BrowserList database

Editor & Toast component refinements

---

packages/components/src/components/icon/icon.tsx

- Fix fetching of icon sprites across origins to avoid CORS issues
- Allow using RemixIcons which don't have a style suffix. To do so, set the `iconStyle` prop to an empty string

Fix fetching of icons across origins

---

packages/components/src/components/button/button.tsx
packages/components/src/components/button/test/button.spec.tsx
packages/components/src/components/editor/editor.tsx
packages/style-material/cssnano.config.js
packages/style-material/src/atoms/button/index.css
packages/style-stencila/cssnano.config.js
packages/style-stencila/src/atoms/button/index.css

Resolves issues with code execution when interfacing with Executa.
Executa expects the code node programming language to be lowercase (e.g. `python', instead of `Python`).
This is done by lowercasing the programming language.
Additionally this PR makes some minor refinements:
- Doesn't [optimize/rename CSS animation keyframes](https://github.com/cssnano/cssnano/tree/master/packages/postcss-reduce-idents#postcss-reduce-idents), this reduces clashes when the components are used in conjunction with other CSS stylesheets, such as from Thema.
- Fixes issue with buttons trapping/persisting the focus ring after being clicked
- Attempts to fix issue with minimal loading button icons not being legible when color was overridden by Thema stylesheets

Fix CodeChunk programming language mapping, and misc. button style fixes

---

stories/molecules/codeChunk/codeChunk.stories.js
stories/molecules/codeExpression/codeExpression.stories.js

While checking the Storybook, I noticed that some of the HTML Microdata (specifically some `itemtype` attributes) were wrong. Since rendering / functioning of component does not depend upon these attributes (other than customisation in themes (?)), it seems better to remove them to avoid confusion.

docs(Storybook): Remove HTML Microdata for code chunk and code expression stories

---

.storybook/preview-head.html
packages/components/src/components/projectGraph/projectGraph.tsx

- Add styles to Storybook container to make fullscreen stories actually fullscreen
- Use canvas centre point for centring the graph.

Centre project graphs

---

packages/components/src/components/editor/components/languageSelect.tsx
stories/atoms/editor/editor.stories.js

This change is due to an issue with Firefox with dynamic optgroup lists.
When re-rendering, Firefox would incorrectly always set the first item
from the first optgroup as selected.
@nokome, this was the only solution I was able to come up with unfortunately.
Down the road we can possibly look into using a third-party component instead of the browser native select elements, which could provide a workaround for this.
Meanwhile, I've added a disabled `option` element as a makeshift divider within the list.

Editor: Remove optgroups from list of languages

---

packages/components/package-lock.json
packages/components/src/components.d.ts
packages/components/src/components/button/readme.md
packages/components/src/components/codeBlock/codeBlock.css
packages/components/src/components/codeBlock/codeBlock.material.css
packages/components/src/components/codeBlock/codeBlock.tsx
packages/components/src/components/codeBlock/readme.md
packages/components/src/components/codeExpression/codeExpression.tsx
packages/components/src/components/codeExpression/languageSelect.tsx
packages/components/src/components/codeExpression/readme.md
packages/components/src/components/codeFragment/codeFragment.css
packages/components/src/components/codeFragment/codeFragment.tsx
packages/components/src/components/codeFragment/readme.md
packages/components/src/components/editor/components/languageSelect.tsx
packages/components/src/components/editor/editor.tsx
packages/components/src/components/editor/languageUtils.ts
packages/components/src/components/editor/readme.md
packages/components/src/components/menu/menu.tsx
packages/components/src/components/menu/readme.md
packages/components/src/components/menuItem/menuItem.tsx
packages/components/src/components/menuItem/readme.md
packages/style-material/src/atoms/menuItem.css
packages/style-stencila/src/atoms/menuItem.css
packages/style-stencila/src/molecules/codeBlock.css
packages/style-stencila/src/molecules/codeExpression.css
packages/style-stencila/src/molecules/codeFragment.css
stories/molecules/codeBlock/codeBlock.stories.js
stories/molecules/codeFragment/codeFragment.stories.js

This PR adds a `stencila-code-fragment` and `stencila-code-block` components (Closes #245, closes #246).
This PR also:
- exposes and allows setting the programming language of CodeFragment and CodeExpression components
- Adds support for `readOnly` mode for all code components. Disabling the editing of the code content, as well as changing of the programming language
- Adds TypeScript syntax support for the Editor component

Add Code Fragment and Code Block components

---

packages/components/src/components.d.ts
packages/components/src/components/code/codeTypes.ts
packages/components/src/components/codeBlock/codeBlock.tsx
packages/components/src/components/codeBlock/readme.md
packages/components/src/components/codeChunk/codeChunk.tsx
packages/components/src/components/codeChunk/readme.md
packages/components/src/components/codeExpression/codeExpression.tsx
packages/components/src/components/codeExpression/readme.md
packages/components/src/components/codeFragment/codeFragment.tsx
packages/components/src/components/codeFragment/readme.md
packages/components/src/components/editor/editor.tsx
packages/components/src/components/parameter/parameter.tsx
packages/components/src/globals/events.ts
packages/components/src/index.ts
stories/molecules/codeFragment/codeFragment.stories.js

Fixes updating of the `executableLanguages` list in the CodeChunk component,
and emits change events fore CodeFragment/CodeChunk components.

fix(Code): Ensure code components have unified interfaces and methods

---

packages/components/src/components/editor/editor.tsx

Keymaps do not override previously defined shortcuts, as such earlier
mappings have higher precedence.

fix(Editor): Update precedence of keymaps
